### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by khionu** [eccentricdevotion/TARDISSonicBlaster#1]
Is this Plugin released for download anywhere? I checked your Bukkit Profile, and it wasn't listed there, and I can't find it via searching.

**Comment by eccentricdevotion** [comment]
Not finished yet, maybe never will be

**Comment by khionu** [comment]
:/ Sorry to hear.

**Comment by eccentricdevotion** [comment]
Builds are on the TARDIS Jenkins server... http://tardisjenkins.duckdns.org:8080/job/TARDISSonicBlaster/
