### ISSUE TITLE
Landlord support

### ISSUE THREAD

**Issue by ThemInspectors** [eccentricdevotion/TARDISSonicBlaster#2]
Even though Landlord is less popular I think it should be added so people don't grief others' Land w/ the blaster. Also could you add support for landlord in the TARDIS plugin? sonic, TARDIS travel etc.

**Comment by eccentricdevotion** [comment]
The Sonic Blaster will probably never be completed, I just don't have time...

Landlord has not been updated for some time either (is it 1.9 compatible?) so unlikely to support it...

**Comment by ThemInspectors** [comment]
It's not been updated in a while, MIT licence, but the only thing that breaks in 1.9 is the sounds.

**Comment by eccentricdevotion** [comment]
Sounds and effects mostly, but Landlord doesn't have an API either...

**Comment by ThemInspectors** [comment]
Also why aren't Issues enabled on the TARDIS github repository?

**Comment by eccentricdevotion** [comment]
Use the Bukkit page for TARDIS issues
